import pandas as pd
import numpy as np

def validate_datasets(ledger_df, gateway_df):
    ledger_count = len(ledger_df)
    gateway_count = len(gateway_df)
    volume_difference = gateway_count - ledger_count
    ledger_total = float(round(ledger_df['amount_usd'].sum(), 2))
    gateway_total = float(round(gateway_df['amount_usd'].sum(), 2))
    ledger_nulls = int(ledger_df.isnull().sum().sum())
    gateway_nulls = int(gateway_df.isnull().sum().sum())
    validation = {
        'ledger_count': ledger_count,
        'gateway_count': gateway_count,
        'volume_difference': volume_difference,
        'ledger_total': ledger_total,
        'gateway_total': gateway_total,
        'ledger_nulls': ledger_nulls,
        'gateway_nulls': gateway_nulls
    }
    return validation

def find_transaction_differences(ledger_df, gateway_df):
    ledger_ids = set(ledger_df['transaction_id'])
    gateway_ids = set(gateway_df['transaction_id'])
    only_in_ledger = ledger_ids - gateway_ids
    only_in_gateway = gateway_ids - ledger_ids
    in_both = ledger_ids & gateway_ids
    result = {
        'only_in_ledger': only_in_ledger,
        'only_in_gateway': only_in_gateway,
        'in_both': in_both
    }
    return result

def build_discrepancy_report(ledger_df, gateway_df, differences):
    only_in_ledger_ids = differences['only_in_ledger']
    missing_in_gateway = ledger_df[ledger_df['transaction_id'].isin(only_in_ledger_ids)].copy()
    missing_in_gateway['issue_type'] = 'Missing in Gateway'
    missing_in_gateway = missing_in_gateway[['transaction_id', 'amount_usd', 'issue_type']].rename(columns={'amount_usd': 'ledger_amount'})

    in_both_ids = differences['in_both']
    ledger_common = ledger_df[ledger_df['transaction_id'].isin(in_both_ids)].copy()
    gateway_common = gateway_df[gateway_df['transaction_id'].isin(in_both_ids)].copy()
    merged = pd.merge(
        ledger_common[['transaction_id', 'amount_usd']].rename(columns={'amount_usd': 'ledger_amount'}),
        gateway_common[['transaction_id', 'amount_usd']].rename(columns={'amount_usd': 'gateway_amount'}),
        on='transaction_id'
    )
    merged['amount_difference'] = merged['ledger_amount'] - merged['gateway_amount']
    amount_mismatch = merged[merged['amount_difference'] != 0].copy()
    amount_mismatch['issue_type'] = 'Amount Mismatch'
    amount_mismatch = amount_mismatch[['transaction_id', 'ledger_amount', 'gateway_amount', 'amount_difference', 'issue_type']]

    report_df = pd.concat([missing_in_gateway, amount_mismatch], ignore_index=True)
    severity_mapping = {
        'Missing in Gateway': 'High',
        'Amount Mismatch': 'Medium'
    }
    report_df['severity'] = report_df['issue_type'].map(severity_mapping)
    return report_df

# Status mapping for consistency
status_mapping = {
    'captured': 'Captured',
    'succeeded': 'Captured',
    'failed e05 timeout': 'Failed',
    'failed': 'Failed',
    'chargeback': 'Chargeback'
}

import pandas as pd
import json
import os
from reconciliation_functions import validate_datasets, find_transaction_differences, build_discrepancy_report, status_mapping

# Load DataFrames (assuming they are already loaded in the main notebook context or need to be reloaded)
# For a standalone script, you would load them here, e.g.:
# ledger = pd.read_csv('path/to/ledger.csv')
# gateway = pd.read_csv('path/to/gateway.csv')
# txns = pd.read_csv('path/to/txns_cleaned_final.csv')

# Ensure output data directory exists
output_data_dir = '01_data/processed'
if not os.path.exists(output_data_dir):
    os.makedirs(output_data_dir)

# --- Reconciliation Workflow ---

# 1. Validation Summary
validation = validate_datasets(ledger, gateway)

# 2. Find Transaction Differences
differences = find_transaction_differences(ledger, gateway)

# 3. Build Discrepancy Report (Amount Mismatches and Missing in Gateway)
report = build_discrepancy_report(ledger, gateway, differences)

# Transactions only in ledger (missing from gateway)
missing_in_gateway_df = ledger[ledger['transaction_id'].isin(differences['only_in_ledger'])]
missing_in_gateway_df.to_csv(os.path.join(output_data_dir, 'missing_in_gateway.csv'), index=False)
print(f"Generated 'missing_in_gateway.csv' with {len(missing_in_gateway_df)} records.")

# Transactions only in gateway (missing from ledger)
missing_in_ledger_df = gateway[gateway['transaction_id'].isin(differences['only_in_gateway'])]
missing_in_ledger_df.to_csv(os.path.join(output_data_dir, 'missing_in_ledger.csv'), index=False)
print(f"Generated 'missing_in_ledger.csv' with {len(missing_in_ledger_df)} records.")

# Create a DataFrame for 'Missing in Gateway' issues (from the 'report' generated by build_discrepancy_report)
missing_in_gateway_issues_df = report[report['issue_type'] == 'Missing in Gateway']
missing_in_gateway_issues_df.to_csv(os.path.join(output_data_dir, 'missing_in_gateway_issues.csv'), index=False)
print(f"Generated 'missing_in_gateway_issues.csv' with {len(missing_in_gateway_issues_df)} records.")

# Create a DataFrame for 'Amount Mismatch' issues
amount_mismatch_issues_df = report[report['issue_type'] == 'Amount Mismatch']
amount_mismatch_issues_df.to_csv(os.path.join(output_data_dir, 'amount_mismatches.csv'), index=False)
print(f"Generated 'amount_mismatches.csv' with {len(amount_mismatch_issues_df)} records.")

# Identify common transactions for status comparison
in_both_ids = differences['in_both']
ledger_common_status = ledger[ledger['transaction_id'].isin(in_both_ids)][['transaction_id', 'status']].copy()
ledger_common_status['status'] = ledger_common_status['status'].str.lower().str.strip().replace(status_mapping, regex=True)
gateway_common_status = gateway[gateway['transaction_id'].isin(in_both_ids)][['transaction_id', 'status']].copy()
gateway_common_status['status'] = gateway_common_status['status'].str.lower().str.strip().replace(status_mapping, regex=True)
status_comparison = pd.merge(
    ledger_common_status.rename(columns={'status': 'ledger_status'}),
    gateway_common_status.rename(columns={'status': 'gateway_status'}),
    on='transaction_id',
    how='inner'
)
status_mismatch_df = status_comparison[status_comparison['ledger_status'] != status_comparison['gateway_status']].copy()
status_mismatch_df['issue_type'] = 'Status Mismatch'
status_mismatch_df['severity'] = 'Medium'
status_mismatch_df.to_csv(os.path.join(output_data_dir, 'status_mismatches.csv'), index=False)
print(f"Generated 'status_mismatches.csv' with {len(status_mismatch_df)} records.")

# Generate final comprehensive reconciliation report
report_missing_in_gateway = pd.DataFrame({
    'transaction_id': list(differences['only_in_ledger']),
    'ledger_amount': ledger[ledger['transaction_id'].isin(differences['only_in_ledger'])]['amount_usd'].values,
    'gateway_amount': 0,
    'difference': ledger[ledger['transaction_id'].isin(differences['only_in_ledger'])]['amount_usd'].values,
    'issue_type': 'Missing in Gateway'
})

report_missing_in_ledger = pd.DataFrame({
    'transaction_id': list(differences['only_in_gateway']),
    'ledger_amount': 0,
    'gateway_amount': gateway[gateway['transaction_id'].isin(differences['only_in_gateway'])]['amount_usd'].values,
    'difference': -gateway[gateway['transaction_id'].isin(differences['only_in_gateway'])]['amount_usd'].values,
    'issue_type': 'Missing in Ledger'
})

amount_mismatches = report[report['issue_type'] == 'Amount Mismatch'].rename(columns={
    'ledger_amount': 'amount_ledger',
    'gateway_amount': 'amount_gateway',
    'amount_difference': 'amount_diff'
})
report_amount_mismatch = pd.DataFrame({
    'transaction_id': amount_mismatches['transaction_id'],
    'ledger_amount': amount_mismatches['amount_ledger'],
    'gateway_amount': amount_mismatches['amount_gateway'],
    'difference': amount_mismatches['amount_diff'],
    'issue_type': 'Amount Mismatch'
})

reconciliation_report = pd.concat([
    report_missing_in_gateway,
    report_missing_in_ledger,
    report_amount_mismatch,
    status_mismatch_df.drop(columns=['ledger_status', 'gateway_status', 'severity'], errors='ignore') # Drop 'severity' here if it was added
])

reconciliation_report['abs_difference'] = reconciliation_report['difference'].abs()
reconciliation_report = reconciliation_report.sort_values(by='abs_difference', ascending=False).drop(columns=['abs_difference'])
reconciliation_report = reconciliation_report.reset_index(drop=True)
reconciliation_report.to_csv(os.path.join(output_data_dir, 'reconciliation_report.csv'), index=False)
print(f"Generated 'reconciliation_report.csv' with {len(reconciliation_report)} records.")

# --- Generate Summary Metrics (JSON) ---
total_financial_impact = float(reconciliation_report['difference'].abs().sum())

in_both_ids_health = differences['in_both']
ledger_common_health = ledger[ledger['transaction_id'].isin(in_both_ids_health)].copy()
gateway_common_health = gateway[gateway['transaction_id'].isin(in_both_ids_health)].copy()
comparison_df = pd.merge(
    ledger_common_health[['transaction_id', 'amount_usd', 'status']].rename(columns={'amount_usd': 'amount_ledger', 'status': 'status_ledger'}),
    gateway_common_health[['transaction_id', 'amount_usd', 'status']].rename(columns={'amount_usd': 'amount_gateway', 'status': 'status_gateway'}),
    on='transaction_id',
    how='inner'
)
comparison_df['amount_diff'] = comparison_df['amount_ledger'] - comparison_df['amount_gateway']
perfectly_matched_transactions = comparison_df[
    (comparison_df['amount_diff'] == 0) &
    (comparison_df['status_ledger'] == comparison_df['status_gateway'])
]
matched_count = len(perfectly_matched_transactions)
total_internal_ledger_count = len(ledger)
health_score_rounded = round((matched_count / total_internal_ledger_count) * 100, 2)

differences_counts = {
    'only_in_ledger_count': len(differences['only_in_ledger']),
    'only_in_gateway_count': len(differences['only_in_gateway']),
    'in_both_count': len(differences['in_both'])
}

total_discrepancy_issues = len(reconciliation_report)
discrepancy_issue_breakdown = reconciliation_report['issue_type'].value_counts().to_dict()

summary_metrics = {
    "validation_metrics": validation,
    "transaction_difference_counts": differences_counts,
    "total_discrepancy_issues": total_discrepancy_issues,
    "discrepancy_issue_breakdown": discrepancy_issue_breakdown,
    "reconciliation_health_score_percentage": health_score_rounded,
    "total_financial_impact_usd": round(total_financial_impact, 2)
}

output_python_dir = '04_python' # Redefine if running standalone
output_json_path = os.path.join(output_python_dir, 'summary_metrics.json')

with open(output_json_path, 'w') as f:
    json.dump(summary_metrics, f, indent=4)
print(f"Generated '{output_json_path}' with summary metrics.")

# --- Generate Health Score CSV ---
health_score_df = pd.DataFrame({
    'metric': ['Reconciliation Health Score', 'Interpretation'],
    'value': [f'{health_score_rounded:.2f}%', "Good (>95%)" if health_score_rounded > 95 else "Average (85-95%)" if 85 <= health_score_rounded <= 95 else "Poor (<85%)"]
})
health_score_df.to_csv(os.path.join(output_data_dir, 'health_score.csv'), index=False)
print("Generated '01_data/processed/health_score.csv'")

# --- Generate Merchant-wise Breakdown CSV ---
# Merge reconciliation_report with ledger to get merchant_id
reconciliation_with_merchant_id = pd.merge(
    reconciliation_report,
    ledger[['transaction_id', 'merchant_id']],
    on='transaction_id',
    how='left'
)

# Then, merge the result with merchants to get merchant_name
# Assuming 'merchants' DataFrame is available
merchant_issue_summary = pd.merge(
    reconciliation_with_merchant_id,
    merchants[['merchant_id', 'merchant_name']],
    on='merchant_id',
    how='left'
)

# Group by merchant_name and issue_type to count issues
merchant_wise_breakdown = merchant_issue_summary.groupby(['merchant_name', 'issue_type']).size().unstack(fill_value=0)
merchant_wise_breakdown.to_csv(os.path.join(output_data_dir, 'merchant_wise_breakdown.csv'))
print("Generated '01_data/processed/merchant_wise_breakdown.csv'")

import pandas as pd

# Ensure `users` and `txns` DataFrames are loaded if this cell is run independently
# users = pd.read_csv('/content/users.csv')
# txns = pd.read_csv('/content/txns_cleaned_final.csv') # assuming this is the cleaned txns

# --- Step 1: Attempt to populate transaction_id and user_id in api_normalized_df ---
# This is a heuristic approach due to `api_normalized_df['transaction_id']` being all null.
# We will try to match on `merchant_id` and `amount` (which is `amount_usd` in txns).

# Create a temporary DataFrame from txns with relevant columns for merging
txns_for_user_enrichment = txns[['merchant_id', 'amount_usd', 'transaction_id', 'user_id']].copy()

# Rename 'amount' in api_normalized_df to 'amount_usd' for consistent merging with txns
# Temporarily rename if 'amount_usd' does not exist as 'amount' in api_normalized_df for this merge
api_normalized_df_temp = api_normalized_df.copy()
api_normalized_df_temp.rename(columns={'amount': 'amount_usd'}, inplace=True)

# Perform a left merge to bring transaction_id and user_id from txns into api_normalized_df
# This merge is based on merchant_id and amount_usd, which might not be unique, so caution is advised.
# We will only take the first match if multiple exist to avoid duplicating api_normalized_df rows.
merged_api_txns = pd.merge(
    api_normalized_df_temp,
    txns_for_user_enrichment,
    on=['merchant_id', 'amount_usd'],
    how='left',
    suffixes=('', '_from_txns') # Add suffix to avoid column name conflicts
)

# Consolidate transaction_id and user_id. Prioritize existing if not null, otherwise take from txns.
api_normalized_df['transaction_id'] = merged_api_txns['transaction_id'].fillna(merged_api_txns['transaction_id_from_txns']).infer_objects(copy=False)
api_normalized_df['user_id'] = merged_api_txns['user_id'].fillna(merged_api_txns['user_id_from_txns']).infer_objects(copy=False)

# --- Step 2: Enrich with currency and payment_method from txns (using newly populated transaction_id) ---
# Now that transaction_id might be populated, re-attempt the merge for currency and payment_method

txns_info_to_merge = txns[['transaction_id', 'currency', 'payment_method']].rename(columns={
    'currency': 'currency_txns_source',
    'payment_method': 'payment_method_txns_source',
})

# Merge api_normalized_df with the renamed txns info
api_normalized_df = pd.merge(
    api_normalized_df,
    txns_info_to_merge,
    on='transaction_id',
    how='left',
    suffixes=('', '_txns_info')
)

# Consolidate columns: prioritize existing api_normalized_df values if not null,
# otherwise use values from txns.
api_normalized_df['currency'] = api_normalized_df['currency'].fillna(api_normalized_df['currency_txns_source']).infer_objects(copy=False)
api_normalized_df['payment_method'] = api_normalized_df['payment_method'].fillna(api_normalized_df['payment_method_txns_source']).infer_objects(copy=False)

# Drop the temporary source columns after consolidation
api_normalized_df.drop(columns=['currency_txns_source', 'payment_method_txns_source'], inplace=True, errors='ignore')

# --- Step 3: Merge with users to get username (using newly populated user_id) ---
# Ensure 'user_id' columns are of compatible types before merging with 'users'
# Convert user_id in api_normalized_df to string to match users['user_id']
api_normalized_df['user_id'] = api_normalized_df['user_id'].astype(str)
users['user_id'] = users['user_id'].astype(str)

# Merge with users to get user_name
api_normalized_df = pd.merge(
    api_normalized_df,
    users[['user_id', 'user_name']],
    on='user_id',
    how='left'
)

# Rename 'user_name' to 'username' to match the original intent
api_normalized_df.rename(columns={'user_name': 'username'}, inplace=True)

print("Enriched API Normalized DataFrame head:")
display(api_normalized_df.head())

print("Missing values in enriched api_normalized_df after enrichment:")
display(api_normalized_df.isnull().sum())